version: 0.2
phases:
    install:
        runtime-versions:
            python: 3.11

    pre_build:
        commands:
            - ls
            - pip install poetry

    build:
        commands:
            - poetry config virtualenvs.create false && poetry install --no-dev
            
artifacts:
    files:
        - './*'
        - './handlers/*'
        - './data_models/*'